### ISSUE TITLE
Improperly returning Promises; HTTP status codes; truthy and falsey values

### ISSUE THREAD

**Issue by ghost** [unfoldingWord-dev/node-gogs-client#1]
# Code Review

A few critiques, as it's happened in our backend code and seems to be spreading due to copy-paste/mimicking. Many of the errors are due to redundancy, e.g. not understanding how Promises return or throw errors.
## Promises

You're doing Promises wrong. This:

``` javascript
_this.createUser = function(user, authUser, notify) {
    return new Promise(function(resolve, reject) {
        var data = user;
        data.send_notify = notify;
        request('admin/users', authUser, data, null).then(function(response) {
            if(response.status == 201) {
                resolve(JSON.parse(response.data));
            } else {
                reject(response);
            }
        }).catch(reject);
    });
};
```

...should be:

``` javascript
_this.createUser = function(user, authUser, notify) {
    // There's no need to have another variable. Objects are pointers/references anyway.
    user.send_notify = !!notify; // the !! forces it to a boolean type
    return request('admin/users', authUser, user, null).then(function (response) {
        if (response.status != 200 || response.status != 201) {
            throw response;
        }
        return JSON.parse(response.data);
    });
};
```

There is no need to create a Promise directly, as the `request` function is returning a Promise. Very rarely do you need to do `new Promise(`. That's only for wrappers. If the function is Promise-style, just return it. And don't worry necessarily about errors. The great thing about Promises is you can attach a `.catch` anywhere in the chain and either continue to propagate it or recover from it.

Another example. This:

``` javascript
_this.deletePublicKey = function(key, user) {
    key = key || null;
    user = user || null;
    return new Promise(function(resolve, reject) {
        if(key !== null && user !== null) {
            request('user/keys/' + key.id, user, null, 'DELETE').then(function(response) {
                response.status === 204 ? resolve() : reject(response);
            });
        } else {
            reject('missing arguments');
        }
    });
};
```

...should be:

``` javascript
_this.deletePublicKey = function(key, user) {
    return request('user/keys/' + key.id, user, null, 'DELETE').then(function (response) {
        if (response.status != 200 || response.status != 201 || response.status != 202 || response.status != 204) {
            throw response;
        }
        return response;
    });
};
```

If an error is thrown, the Promise is rejected and can be caught anywhere in the chain with a `.catch` block. Again: **If you have code that does `return new Promise(...` you're probably doing something wrong** (unless you're converting a callback-style function to a Promise, but even then you should be using a wrapper function, as you've done with `request`).

Also, in Javascript, **don't enforce the existence of arguments**; if something breaks, it breaks. No need to throw a 'missing arguments' or whatnot. If you did that, every function would have that, and you'd end up with a weird, dynamically-statically-typed language that still broke at runtime...
## HTTP Status Codes

Additionally, check this out for HTTP response codes: [HTTP Statuses](https://httpstatuses.com/). A server is not required to return a specific code, so you should (most of the time) check for ranges. E.g., returning a `201` or a `204` instead of a `200` is entirely optional. Many servers just always return a `200`. I'm just checking specific values, but you could check against a range (`<=`, etc) or use a switch statement with fall-throughs.

In checking the status codes, I am doing a `throw` first. Anything that throws or returns do to a condition should be done first. This makes it easier to read and eliminates an `else` statement.
## Truthy and Falsey Values

You're doing checks like this:

``` javascript
if(data === null) {
    // blah blah blah
}
```

You should be doing:

``` javascript
if (!data) {
    // blah blah blah
}
```

...because it works if the data/variable is `null`, `undefined`, `false`, `0`, or `''` (empty string). Empty parameters (when you call a function but don't pass a certain parameter) are passed as `undefined`. There's very rarely a need to make them `null`. Null values are only useful in objects, so that you can tell if the value is there or not.

Here's a use-case for `null` values:

``` javascript
var someObject = {
    name: 'Bob',
    hasPaidTaxes: false
};

// later in some code...
someObject.hasPaidTaxes = null;
// Now I can tell that we don't know if Bob has paid their taxes, so long as we use === and not ==
if (someObject.hasPaidTaxes === null) {
    // We don't know if he's paid his taxes
}

// and our other code for checking still works

if (someObject.hasPaidTaxes) {
    // blah blah blah
}
if (!someObject.hasPaidTaxes) {
    // blah blah blah
}

// If we had done undefined instead of null, we'd have to use
if ('hasPaidTaxes' in someObject) {
    // blah blah blah
}
// or...
if (someObject.hasOwnProperty('hasPaidTaxes')) {
    // blah blah blah
}

// ... but it can be easier to explicitly check against a null, because it can difficult to remember to "delete" a property (either via the "delete" command or via setting it to undefined)
```

Again, the above is just a use case. It's essentially a cheap way to have a True/False/Maybe boolean. For the majority of the time, I'd recommend only using `null` values in objects so that you can tell if was on purpose or not. For variables, just use truthy/falsey values. Rule of thumb.

Many people are against using `==` and suggest always using `===`, but I disagree. There are instances where one or the other is more valid. If you're using `==`, then you're checking whether it's truthy or falsey. Most of the time, this can be reduced to a `!value` or `!!value` or even `value`, particularly in if statements or variable assignments. If you're using `===`, then you should be checking against a particular value for a particular reason.

**Comment by da1nerd** [comment]
cool. Thanks for the tips.
